---
title: "Visualise ascotracR output"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visualise ascotracR output}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
  %\usepackage{extrafont}
  %\VignetteDepends{cowplot}
  %\VignetteDepends{ggplot2}
  %\VignetteDepends{ggpubr}
  %\VignetteDepends{readxl}
  %\VignetteDepends{ggpubr}
  %\VignetteDepends{lubridate}
  %\VignetteDepends{viridis}
  %\VignetteDepends{showtext}
  %\VignetteDepends{here}
  %\VignetteDepends{patchwork}
  %\VignetteDepends{classInt}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
knitr::opts_chunk$set(progress = TRUE, verbose = TRUE)
knitr::opts_chunk$set(
  echo = TRUE,
  fig.width = 7,
  fig.height = 7,
  fig.align = "centre"
)
```

```{r fonts, include=FALSE, message=FALSE, eval=FALSE}
# Note that GhostScript needs to be installed at the system level for the PS files to be generated.
# MacOS users can use `brew install ghostscript`
# 
# Windows users can follow these directions:
# 1.	Go to the GhostScript website (https://www.ghostscript.com/download/gsdnld.html)
# 2.	Download the windows installer suitable for your machine
# 3.	Run the installer file which you downloaded and follow the prompts
# 4.	After running the installer click the windows "Start" button and type "Edit environment variables for your account" and open
# 5.	In the tab 'Advanced' click the button at the bottom 'Environment Variables...'
# 6.	Under 'System variables' find the variable 'Path', select 'Path' and click the 'Edit' button
# 7. 	Select a new line and copy the Ghostscript 'bin' folder location into the field.
# 7.1	If you installed ghostscript to the default folder location; then the folder location will likely be "C:\Program Files\gs\gs9.52\bin", the version number (9.52) may differ.
# 8.	Save and exit the environmental variables window
# This chunk is then run only if knitting on new computer that the files have not been generated on
# this is necessary to embed fonts in .eps files 
library("extrafont")
if (.Platform$OS.type == "windows") {
   font_import(pattern = "arial", prompt = FALSE)
   loadfonts(device = "postscript", quiet = TRUE)
} else {
   font_import(pattern = "Arial", prompt = FALSE)
   loadfonts(device = "postscript", quiet = TRUE)
}
```

## Load libraries 

```{r libraries, message=FALSE, echo=TRUE, warning=FALSE}
library("readxl")
library("cowplot")
library("ggplot2")
library("ggpubr")
library("grDevices")
library("dplyr")
library("lubridate")
library("viridis")
library("showtext")
library("readr")
library("here")
library("patchwork")
library("classInt")
library("extrafont")
library("knitr")
library("clifro")

extrafont::loadfonts()
```

### Wind rose

Import wind direction data and covert wind direction from text to degrees

```{r}
wind_dat <-
  read_excel("data/wind_data_for_wind_rose.xlsx",
             col_types = c("date","text", "numeric", "skip", "text")) %>%
  mutate(
    wind_direction = case_when(
      avg_wind_direction == "N" ~ "0",
      avg_wind_direction == "NbE" ~ "11.25",
      avg_wind_direction == "NNE" ~ "22.5",
      avg_wind_direction == "NEbN" ~ "33.75",
      avg_wind_direction == "NE" ~ "45",
      avg_wind_direction == "NEbE" ~ "56.25",
      avg_wind_direction == "ENE" ~ "67.5",
      avg_wind_direction == "EbN" ~ "73.5",
      avg_wind_direction == "E" ~ "90",
      avg_wind_direction == "EbS" ~ "101.2",
      avg_wind_direction == "ESE" ~ "112.5",
      avg_wind_direction == "SEbE" ~ "123.8",
      avg_wind_direction == "SE" ~ "135.1",
      avg_wind_direction == "SEbS" ~ "146.3",
      avg_wind_direction == "SSE" ~ "157.6",
      avg_wind_direction == "SbE" ~ "168.8",
      avg_wind_direction == "S" ~ "180",
      avg_wind_direction == "SbW" ~ "191.2",
      avg_wind_direction == "SSW" ~ "202.5",
      avg_wind_direction == "SWbS" ~ "213.8",
      avg_wind_direction == "SW" ~ "225",
      avg_wind_direction == "SWbW" ~ "236.2",
      avg_wind_direction == "WSW" ~ "247.5",
      avg_wind_direction == "WbS" ~ "258.8",
      avg_wind_direction == "W" ~ "270",
      avg_wind_direction == "WbN" ~ "281.2",
      avg_wind_direction == "WNW" ~ "292.5",
      avg_wind_direction == "NWbW" ~ "303.8",
      avg_wind_direction == "NW" ~ "315",
      avg_wind_direction == "NWbN" ~ "326.2",
      avg_wind_direction == "NNW" ~ "337.5",
      avg_wind_direction == "NbW" ~ "348.8",
      TRUE ~ avg_wind_direction
    )
  ) %>%
  mutate(location=as.factor(location))
```


```{r plot-wind-rose, message=FALSE}
fig_1 <-
   with(
      wind_dat,
      windrose(
         wind_speed,
         wind_direction,
         facet = location,
         n_col = 2,
         legend_title = "Wind speed (m/s)"
      )
   )

fig_1 <-
   fig_1 +
   scale_fill_viridis_d(name = "Wind Speed (m/s)", direction = -1, option = "cividis") +
   xlab("") +
   theme_pubclean(base_family = "Arial Unicode MS")

```

```{r save-figure}
ggsave(
   here("man", "figures/Fig1.png"),
   width = 9,
   height = 9,
   units = "in",
   dpi = 600
)

cairo_ps(
   here("man", "figures/Fig1.eps"),
   family = "Arial Unicode MS"
)
fig_1
dev.off()
```

